import ToggleLightDark from '@/components/theme/toggleLightDark';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { type ReactNode } from 'react';
import './globals.css';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html
            lang='en'
            suppressHydrationWarning
        >
            <head />
            <body className={inter.className}>
                <Providers>
                    <ToggleLightDark />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
